# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: mii-ig-molgen-de-v2026
canonical: https://www.medizininformatik-initiative.de/fhir/ext/modul-molgen
title: "IG MII Modul Molekulargenetischer Befundbericht"
name: MII_IG_MolGen_DE
status: active
version: "2026.0.0-ballot"
fhirVersion: 4.0.1
language: de
copyrightYear: 2021+
releaseLabel: ci-build
packageId: de.medizininformatikinitiative.kerndatensatz.molgen
publisher:
  name: Medizininformatik-Initiative
  url: https://www.medizininformatik-initiative.de/
  email: info@medizininformatik-initiative.de
dependencies:
  hl7.fhir.uv.genomics-reporting: 3.0.x
  de.medizininformatikinitiative.kerndatensatz.meta: 2026.0.x
  de.basisprofil.r4: 1.5.x
  de.medizininformatikinitiative.kerndatensatz.diagnose: 2025.0.x
  de.medizininformatikinitiative.kerndatensatz.biobank: 2026.0.0-ballot
  hl7.terminology.r4: 6.1.x

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#menu:
#  Home: index.html
#  Artifacts: artifacts.html
